# -*- coding: utf-8 -*-
"""week 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WPEnBXXhRy9wPhNww_8HWc-0i6Qm73w0
"""

list = ["maulana",20,"depok",4.5]
list.append("mahasiswa",)
list.insert(0,"nurul fikri")

list1=[1,2,3,4,5,6]
list2=[4,5,6]
add=list1+list2

print(add)

print(list)
print("profesi saya ",list[4])
print(list[0])

cuaca=input ("apakah cuacar hari ini? ")

match cuaca:
  case "hujan":
     print("naik gocar")
  case "cerah":
     print("naik motor")
  case "badai":
     print("tidak kuliah")
  case _:
     print("salah input cuaca")

#Tugas1

NamaKendaraan = "Motor"
JenisKendaraan = "Honda"
CcKendaraan = 150
WarnaKendaraan = "Coklat"
RodaKendaraan = 2

list = [NamaKendaraan,JenisKendaraan,CcKendaraan,WarnaKendaraan,RodaKendaraan]

print (list)

HargaKendaraan = 100000
TipeKendaraan = "Matic"
list.append(HargaKendaraan)
list.append(TipeKendaraan)

print (list)

MerkKendaraan = "Beat Deluxe"
list.insert(2, MerkKendaraan)

print(list)

#Tugas2

nilai = int(input("""Mari Menghitung
pilih 1 jika menghitung luas persegi
pilih 2 jika menghitung luas lingkaran
pilih 3 jika menghitung luas segitiga """))

match nilai:
  case 1 :
    sisi = int(input("masukan sisi "))
    total = sisi * sisi
    print("luas persegi adalah ",total)
  case 2 :
    jari = int(input("masukan jari-jari "))
    total = 3.14 * jari * jari
    print("luas lingkaran adalah ",total)
  case 3 :
    alas = int(input("masukan alas "))
    tinggi = int(input("masukan tinggi "))
    total = alas * tinggi / 2
    print("luas segitiga adalah ",total)
  case _:
    print("salah masukan input")